[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/tasarla"
  to = "/tasarla.html"
  status = 200
[[redirects]]
  from = "/galeri"
  to = "/galeri.html"
  status = 200
[[redirects]]
  from = "/claudeninsahibiagritutaklimi"
  to = "/claudeninsahibiagritutaklimi.html"
  status = 200
[[redirects]]
  from = "/icerik"
  to = "/icerik.html"
  status = 200
[[redirects]]
  from = "/silivri"
  to = "/silivri.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
